i18n : intllib po/pot method, added french translation
MinetestForFun/areas pull request #1
Opened 2017-08-05 05:46 UTC by fat115

plural forms can be improved (todo)

---
traduction quasi complète, les formes plurielles sont à améliorer.
à vous de voir ;)

2017-08-05 08:12 UTC, ObaniGemini commented
Not a bad idea, but was it really needed to duplicate each return line ?

2017-08-05 08:13 UTC, ObaniGemini commented
MFF is known to be a mass of bloat code, should we add to the mass ? @MinetestForFun/devs

2017-08-05 11:36 UTC, fat115 commented
What do you mean exactly by "duplicate each return line" ?

2017-08-05 11:51 UTC, ObaniGemini commented
@fat115 : don't mind what I said, I totally misread the GIT diff (I suppose I'm sleepy...).
I'm not against it, I've seen some players complaining about some things not being translated in-game, so why not ?

2017-09-04 11:37 UTC, LeMagnesium commented
I'm not sure that making areas conditionally load intllib is worth it, especially since MinetestForFun's modpack is already bloated with tons of code, and most people over on our servers understand english, so I doubt translations are that useful. The UI is also intuitive enough to understand after a short while.
I could, however, merge your changes into a separate branch, for an alternate version of areas with translation support, in case someone out there is interested in getting i18n translations.

2019-09-23 23:34 UTC, Panquesito7 requested changes

2019-09-23 23:34 UTC, Panquesito7 commented on init.lua
>  if minetest.setting_getbool("log_mod") then
Please use the new settings method.
```suggestion
if minetest.settings:get_bool("log_mods") then
```

2019-10-15 02:05 UTC, Panquesito7 approved these changes
Looks good. 👍

2019-10-15 08:29 UTC, Darcidride commented
@Panquesito7 Seems good to me, you can merge it :)

2019-10-15 23:33 UTC, merged